### ISSUE TITLE
你好，关于文章分层目录的问题。

### ISSUE THREAD

**Issue by zxfccmm4** [chiperman/gridea-theme-porky#1]
你好，非常喜欢这个主题。
我也下载进行布置了。
但是发现文章没有目录分层这个功能。请问是否有计划添加？

**Comment by chiperman** [comment]
抱歉我没太能理解你所指的目录分层是什么意思，能否给出一个具体例子或者截图供我参考一下。

**Comment by zxfccmm** [comment]
> 抱歉我没太能理解你所指的目录分层是什么意思，能否给出一个具体例子或者截图供我参考一下。

就是侧边栏 文章的大纲目录  [左侧的文章目录](https://zxfccmm.cn/ios-15-beta-chu-ti-yan/)

**Comment by chiperman** [comment]
有这个计划，但是目前没有时间进行添加，还需要考虑下美观和一体性。
所以只能暂时等等，如果你有更好的实现方式，也欢迎你贡献你的代码或者是点子。

**Comment by zxfccmm4** [comment]
> 有这个计划，但是目前没有时间进行添加，还需要考虑下美观和一体性。
> 所以只能暂时等等，如果你有更好的实现方式，也欢迎你贡献你的代码或者是点子。

Thank You

**Comment by zxfccmm4** [comment]
![WX20210616-163746](https://user-images.githubusercontent.com/17553115/122187106-4d8c9180-cec1-11eb-8690-f1a5cd571263.png)
我觉得设置成这样可能比较美观？

**Comment by zxfccmm4** [comment]
> > ![WX20210616-163746](https://user-images.githubusercontent.com/17553115/122187106-4d8c9180-cec1-11eb-8690-f1a5cd571263.png) 我觉得设置成这样可能比较好看？
> 
> 感谢提供图片，望能不能提供下网址供我参考一下。明年春节会考虑整个主题。
[
](https://www.ouorz.com/post/731)
