### ISSUE TITLE
列表中未渲染 LaTeX

### ISSUE THREAD

**Issue by liuzimingc** [chiperman/gridea-theme-porky#7]
如题。此外有没有方法可以隐藏下方的 `Theme: [Porky ](https://github.com/chiperman/gridea-theme-porky). Powered by [Gridea](https://gridea.dev/)` 呢？原因是 Porky 后面打了个空格不好看（）

**Comment by chiperman** [comment]
我经过测试目前看起来是正常的，请查看是否语法问题。
测试文章如下：
```
# LaTeX在列表中的示例

## 无序列表

- 使用LaTeX插入数学公式：$E=mc^2$
- 使用LaTeX插入分数：$\frac{a}{b}$
- 使用LaTeX插入上标：$x^2$
- 使用LaTeX插入下标：$x_1$

## 有序列表

1. 使用LaTeX插入希腊字母：$\alpha$
2. 使用LaTeX插入积分：$\int_{0}^{\infty} e^{-x^2} dx$
3. 使用LaTeX插入根号：$\sqrt{2}$
4. 使用LaTeX插入矩阵：
   $$
   \begin{pmatrix}
   1 & 2 \\
   3 & 4
   \end{pmatrix}
   $$

## 引用列表

> 使用LaTeX插入定理：
> 
> **定理**：勾股定理表达式为 $a^2 + b^2 = c^2$，其中 $a$、$b$ 和 $c$ 分别为直角三角形的两条直角边和斜边。

## 嵌套列表

- 使用LaTeX插入微分方程：
  $$
  \frac{d^2y}{dx^2} + \omega^2 y = 0
  $$
  这是一个简单的谐振子微分方程。

  - 初始条件：
    - $y(0) = 0$
    - $\frac{dy}{dx}\Bigg|_{x=0} = v_0$
```
![屏幕截图_15-3-2024_161748_localhost](https://github.com/chiperman/gridea-theme-porky/assets/34889778/6aac34ca-5dd7-42c8-b165-e78bb2ba5f14)



针对隐藏版权说明，通过删除这段内容的确可以隐藏，但是为了尊重他人成果和版权，我还是希望保留，为此基础配置里面也提供了自定义的底部信息供你添加。

Porky 后面的空格的确是我的失误，我会修改样式，重新拉取最新的版本即可。也感谢你使用我的主题，如果喜欢可以点个 Star。

![image](https://github.com/chiperman/gridea-theme-porky/assets/34889778/71f1bb6d-5264-4a28-b46f-1a0063f0a300)

**Comment by chiperman** [comment]
已经更新为:`Theme：Porky | Powered by Gridea`，如果十分想要去掉底部信息，请前往修改主题文件夹下的 `gridea-theme-porky\templates\includes\footer.ejs` 文件即可。

**Comment by liuzimingc** [comment]
哦哦，非常感谢！！1

**Comment by liuzimingc** [comment]
好像不对啊，列表中渲染效果和普通文本不一样？

**Comment by liuzimingc** [comment]
从给的那个图就看得出来（

**Comment by chiperman** [comment]
> 好像不对啊，列表中渲染效果和普通文本不一样？

不太理解你的意思，你希望是什么效果？

**Comment by liuzimingc** [comment]
比如说用相同的文本，把主题换成  Fly，应该是那样的效果。这里不方便截图（

**Comment by chiperman** [comment]
这是 Fly 主题下的截图

![image](https://github.com/chiperman/gridea-theme-porky/assets/34889778/bb7bf3b6-175d-4175-85b2-fde648bfc6d3)

**Comment by liuzimingc** [comment]
是的，这两个效果不一样啊？（）

**Comment by liuzimingc** [comment]
那个 \alpha 应该比较看得出来差别？

**Comment by chiperman** [comment]
你是说字体不一样？如果可以，你最好直接指出具体的差异。

**Comment by liuzimingc** [comment]
或许是字体的问题？但是写在正文中的和写在列表里的渲染不一样就很怪（

**Comment by liuzimingc** [comment]
破案了，渲染没问题，单纯字体不一样，有什么办法调整吗🤔 因为看 Fly 的那种看习惯了（）

**Comment by chiperman** [comment]
你可以自己修改 .less 里面的 `font-family` 的值，仓库主题不会修改。

**Comment by liuzimingc** [comment]
非常抱歉，但是这个 font-family 好像不针对 latex？

**Comment by chiperman** [comment]
试着修改 `assets\styles\lib\katex.less` 这个文件

**Comment by liuzimingc** [comment]
似乎把 `katex.less` 改成空的就行了？？？现在不方便弄回去看看效果

**Comment by liuzimingc** [comment]
好像不行，，，可以~~不要脸地~~问一下应该怎么弄吗，非常感谢！！！已经 Star 了！！1

**Comment by liuzimingc** [comment]
整了好久还是失败了 /ll

**Comment by liuzimingc** [comment]
@chiperman 作者大大还在嘛 (｡･∀･)ﾉ

**Comment by chiperman** [comment]
不好意思我最近实在是太忙了，按理说就是这个文件，你可以参考下官方默认的主题和其他主题的写法和设置。我大概看了下，官方主题直接引用了 `<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css">`。

**Comment by chiperman** [comment]
你可以用 F12 控制台来看是否生效，或者参考喜欢的主题的字体，然后试着模仿它的做法。

**Comment by liuzimingc** [comment]
> 你可以用 F12 控制台来看是否生效，或者参考喜欢的主题的字体，然后试着模仿它的做法。

~~好像不对，不光是字体的问题，渲染确实有点问题，参见我写的博客（链接回去放，现在被隐藏了）~~
