### ISSUE TITLE
有些语法解析不出来

### ISSUE THREAD

**Issue by xiaoyangst** [chiperman/gridea-theme-porky#8]
cmake的代码解析不出来，而且前面第一行会多出一个空格，这个项目是不是已经不打算维护了？

**Comment by chiperman** [comment]
暂时没有维护的精力了，可以自己 fork 后修改。

**Comment by xiaoyangst** [comment]
> 暂时没有维护的精力了，可以自己 fork 后修改。

把markdown语法中添加的代码识别删除即可
